### ISSUE TITLE
TypeError for width in fingercounting.js

### ISSUE THREAD

**Issue by sanjayen** [cowlicks/privacypossum#69] opened 2018-06-17 16:21 UTC
Firefox 60.0.2 64bit
Privacy Possum 2018.6.10

Apologies, but I do not know how to access the Javascript console for the extension. I tried using both popup.debug() and possum.prettyLog() commands in the console but they both gave me an error.

Here's my problem - I keep on seeing this error message in the browser console;
TypeError: can't redefine non-configurable property "width"

Checking the extension ID, I understood that Privacy Possum was creating these errors. Here's the complete stack trace.

ObjectOrReflectDefineProperty self-hosted:4228:16

defineProperty self-hosted:4244:5

wrapMethod moz-extension://39e1e49a-221f-4679-862f-b2cf7d474084/js/web_accessible/fingercounting.js:199:5

Counter moz-extension://39e1e49a-221f-4679-862f-b2cf7d474084/js/web_accessible/fingercounting.js:169:7

<anonymous> moz-extension://39e1e49a-221f-4679-862f-b2cf7d474084/js/web_accessible/fingercounting.js:259:19

<anonymous> moz-extension://39e1e49a-221f-4679-862f-b2cf7d474084/js/web_accessible/fingercounting.js:3:2

I am using a Screen Resolution Spoof userscript which sets a defined height and width of the browser window. Is this causing a conflict with Privacy Possum? The userscript can be found at;
https://greasyfork.org/en/scripts/29352-screen-resolution-spoof

**Comment by cowlicks** [comment] 2018-07-03 20:38
Yes, this is conflicting Privacy Possum. Both projects call [`Object.defineProperty`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) on things like `window.screen.width`, and leave the redefined thing as "non-configurable". We do this [here](https://github.com/cowlicks/privacypossum/blob/4709d1da72bb142c2a08ec2ca1644e81bd0e808e/src/js/web_accessible/fingercounting.js#L191-L207) and the code for that project is [here](https://greasyfork.org/en/scripts/29352-screen-resolution-spoof/code).

The solution is to fail better in cases like this. Probably by wrapping the `defineProperty` call in a `try/catch`.

**Comment by cowlicks** [comment] 2018-07-03 23:49
Hi @sanjayen it looks like the part  `ObjectOrReflectDefineProperty self-hosted:4228:16` is not coming from the linked userscript, or from privacy possum. I think there is a third thing, probably another userscript, or the extension you use to load user scripts.

What extension do you use to load userscripts? And what other userscripts do you have installed?

I searched greasyfork's scripts for "ObjectOrReflectDefineProperty" but didn't find anything. I also tried reproducing this issue with Greasemonkey 4.5.

**Comment by sanjayen** [comment] 2018-07-04 02:14
Hi @cowlicks I use Violentmonkey v2.9.5 [https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/] as the userscript manager. I use the following userscripts;

Conceal history.length
Conceal window.name
Clear window.opener
from 
https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.2.1-User-Scripts

Absolute Enable Right Click & Copy
from
https://greasyfork.org/en/scripts/23772-absolute-enable-right-click-copy
(I was using v1.8.4 but updated today to v1.8.6)

and lastly the Screen Resolution Spoof which you already are aware of.

The error in the console (ObjectOrReflectDefineProperty self-hosted:4486:16) is not clickable unlike the other code messages. How do I debug this to find the culprit?

**Comment by cowlicks** [comment] 2018-07-08 17:59
Thanks @sanjayen  I was able to confirm that this issue is from the Resolution Spoof + Violentmonkey. So #77 should fix this. I plan on making a release today.

**Comment by r-a-y** [comment] 2018-07-09 16:20
Author of Screen Resolution Spoof userscript here.

I haven't looked through the entire source code, but was wondering why you randomize the width:
https://github.com/cowlicks/privacypossum/blob/5182417aae5f71fbb5db690ebe2b675ff06dd249/src/js/web_accessible/fingercounting.js#L132

Wouldn't that make you more trackable?

Great extension BTW.

**Comment by cowlicks** [comment] 2018-07-12 04:44
Hi @r-a-y thanks for your question:
>  Wouldn't that make you more trackable?

It stops most popular fingerprinting tools from uniquely identifying you.

The value is only randomized when someone is fingerprinting by aggregating a bunch of fingerprinting vectors. The randomized values are only given to the script on the page detected doing this. And a new random value is given every time this is accessed.

Fingerprinting tools usually aggregate multiple fingerprinting vectors to produce a more accurate fingerprint. This heuristic and strategy depends on this behavior. 

Also I forgot to close this when #77 was merged, oops.

**Closed by cowlicks** 2018-07-12 04:44 UTC
Labels: fingerprinting, need more info
